# Generated by Django 5.2.9 on 2025-12-18 14:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='영양소 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDLST_REPORT_NO', models.CharField(max_length=20, unique=True, verbose_name='품목제조보고 번호 (고유 ID)')),
                ('PRDLST_NM', models.CharField(max_length=255, verbose_name='제품명')),
                ('BSSH_NM', models.CharField(max_length=100, verbose_name='제조사/판매사')),
                ('LCNS_NO', models.CharField(max_length=20, verbose_name='인허가 번호')),
                ('PRMS_DT', models.CharField(max_length=10, verbose_name='허가(신고) 일자')),
                ('POG_DAYCNT', models.CharField(max_length=50, verbose_name='소비기한 (기간)')),
                ('PRDT_SHAP_CD_NM', models.CharField(max_length=50, verbose_name='제품 형태 (예: 캡슐, 분말)')),
                ('DISPOS', models.CharField(max_length=255, verbose_name='성상 (제품의 외관)')),
                ('PRIMARY_FNCLTY', models.TextField(verbose_name='주된 기능성')),
                ('NTK_MTHD', models.CharField(max_length=255, verbose_name='섭취방법')),
                ('IFTKN_ATNT_MATR_CN', models.TextField(verbose_name='섭취시 주의사항')),
                ('CSTDY_MTHD', models.CharField(blank=True, max_length=255, verbose_name='보관 방법')),
                ('STDR_STND', models.TextField(verbose_name='기준 규격')),
                ('RAWMTRL_NM', models.TextField(verbose_name='원재료')),
                ('SHAP', models.CharField(blank=True, max_length=100, null=True, verbose_name='SHAP 필드 (JSON 원본 유지)')),
                ('CRET_DTM', models.CharField(max_length=14, verbose_name='최초 생성 일시 (JSON 원본)')),
                ('LAST_UPDT_DTM', models.CharField(max_length=14, verbose_name='최종 수정 일시 (JSON 원본)')),
                ('cover', models.URLField(blank=True, null=True, verbose_name='제품 이미지 URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pills', to='pills.category', verbose_name='대표 카테고리')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='substances',
            field=models.ManyToManyField(related_name='categories', to='pills.substance', verbose_name='포함 영양소'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('eating_date', models.DateField(default=datetime.date.today)),
                ('cover_img', models.ImageField(blank=True, upload_to='thread_cover_img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_threads', to=settings.AUTH_USER_MODEL)),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pills.pill')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pills.thread')),
            ],
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens_info', to='pills.pill')),
            ],
            options={
                'unique_together': {('pill', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance_name', models.CharField(max_length=255, verbose_name='영양소 이름 (중복 저장)')),
                ('value', models.FloatField(verbose_name='함량 값')),
                ('unit', models.CharField(max_length=50, verbose_name='함량 단위')),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_details', to='pills.pill', verbose_name='제품')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pill_details', to='pills.substance', verbose_name='영양소')),
            ],
            options={
                'unique_together': {('pill', 'substance')},
            },
        ),
    ]
