# Generated by Django 5.2.9 on 2025-12-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="substance",
            name="efficacy",
            field=models.TextField(default="데이터 설명", verbose_name="효능 및 효과"),
        ),
        migrations.AddField(
            model_name="substance",
            name="recommended_intake",
            field=models.TextField(default="데이터 설명", verbose_name="권장 섭취량"),
        ),
        migrations.AddField(
            model_name="substance",
            name="side_effects",
            field=models.TextField(
                default="데이터 설명", verbose_name="부작용 및 주의사항"
            ),
        ),
    ]
