# Generated by Django 5.2.9 on 2025-12-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pills", "0002_substance_efficacy_substance_recommended_intake_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pill",
            name="mall_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pill",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pill",
            name="purchase_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
