# Generated by Django 5.2.9 on 2025-12-20 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0002_substance_efficacy_substance_recommended_intake_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='pills.pill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_pills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pill')},
            },
        ),
    ]
