# Generated by Django 5.2.9 on 2025-12-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pills", "0003_pill_mall_name_pill_price_pill_purchase_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="pill",
            name="amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
