# Generated by Django 5.2.9 on 2025-12-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0004_custompill'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompill',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
