# Generated by Django 5.2.9 on 2025-12-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pills", "0004_pill_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pill",
            name="amount",
        ),
    ]
