# Generated by Django 5.2.9 on 2025-12-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pills", "0005_remove_pill_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="pill",
            name="amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="pill",
            name="unit_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
