# Generated by Django 5.2.9 on 2025-12-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0005_custompill_ingredients'),
        ('pills', '0006_pill_amount_pill_unit_type'),
    ]

    operations = [
    ]
