# Generated by Django 5.2.9 on 2025-12-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_genres',
            field=models.ManyToManyField(blank=True, related_name='users', to='pills.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
