# Generated by Django 5.2.9 on 2025-12-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_allergy_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.allergy'),
        ),
    ]
