# Generated by Django 5.2.9 on 2025-12-24 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_refresh_token', models.TextField(blank=True, null=True)),
                ('google_access_token', models.TextField(blank=True, null=True)),
                ('is_linked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
